// UGC bench — try Seedream presenters × Seedance scripts. Test tool, session only.
import { UgcBench } from "@/components/ugc/ugc-bench";

export const metadata = { title: "UGC bench" };

export default function UgcBenchPage() {
  return (
    <main className="mx-auto max-w-[1600px] px-6 py-8">
      <header className="mb-4 space-y-1">
        <span className="text-eyebrow">Test bench</span>
        <h1 className="font-display text-3xl text-neutral-900">Seedream × Seedance</h1>
        <p className="max-w-2xl text-sm text-neutral-500">
          Each row is a presenter generated by Seedream. Each tile is a script that Seedance turns
          into a video with that presenter.
        </p>
      </header>
      <UgcBench />
    </main>
  );
}
