"use client";

import { useState } from "react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { Skeleton } from "@/components/ui/skeleton";
import { Textarea } from "@/components/ui/textarea";
import type { useAvatarVoicePreview } from "@/hooks/use-avatar-voice-preview";
import {
  AVATAR_VOICE_PREVIEW_LINE_MAX, AVATAR_VOICE_PREVIEW_SECONDS, AVATAR_VOICE_SAMPLE_SECONDS,
} from "@/lib/avatars/constants";
import {
  defaultVoicePreviewLine, isVoicePreviewStale, voicePreviewMode, type VoicePreviewMode,
} from "@/lib/avatars/voice-preview";
import type { Avatar } from "@/lib/avatars/schema";
import { AvatarCreditCost } from "./avatar-credit-cost";
import { AvatarVoiceSample } from "./avatar-voice-sample";

type Props = {
  avatar: Avatar;
  preview: ReturnType<typeof useAvatarVoicePreview>;
  /** The voice is being saved — a preview now would use the one being replaced. */
  disabled: boolean;
};

const COPY: Record<VoicePreviewMode, { blurb: string; cta: string; again: string }> = {
  named: {
    blurb: `A ${AVATAR_VOICE_PREVIEW_SECONDS}-second clip of the front image speaking in this voice.`,
    cta: "Generate preview",
    again: "Regenerate preview",
  },
  native: {
    blurb:
      `A ${AVATAR_VOICE_SAMPLE_SECONDS}-second Seedance clip. The voice it invents is saved as this ` +
      "avatar's voice reference and sent with every later video, so the voice stays the same.",
    cta: "Generate voice & reference",
    again: "Generate a new voice",
  },
};

// D294, D296 — hear and see the avatar speak. What runs depends on the declaration: a named
// voice is applied to a Gemini Omni clip, while the engine's own voice is generated by Seedance
// and kept as the avatar's reference audio.
export function AvatarVoicePreview({ avatar, preview: p, disabled }: Props) {
  // Null until the operator types: the box then follows the last preview's line, or the default.
  const [typed, setTyped] = useState<string | null>(null);
  const mode = voicePreviewMode(avatar);
  const line = typed ?? p.preview?.line ?? defaultVoicePreviewLine(avatar.name);
  const busy = p.starting || p.running;
  const clip = p.preview?.status === "succeeded" ? p.preview : null;
  const failed = p.preview?.status === "failed" ? p.preview : null;
  if (!mode) return null;
  const copy = COPY[mode];

  return (
    <div className="flex w-full max-w-md flex-col gap-3 rounded-xl border bg-card p-3">
      <div>
        <p className="text-eyebrow text-muted-foreground">Preview</p>
        <p className="mt-1 text-xs text-muted-foreground">{copy.blurb}</p>
      </div>

      <div className="flex flex-col gap-1.5">
        <Label htmlFor="avatar-voice-preview-line">What the avatar says</Label>
        <Textarea
          id="avatar-voice-preview-line"
          value={line}
          rows={2}
          maxLength={AVATAR_VOICE_PREVIEW_LINE_MAX}
          disabled={busy}
          onChange={(e) => setTyped(e.target.value)}
        />
      </div>

      <Button
        variant={clip ? "outline" : "default"}
        className="self-start"
        disabled={disabled || busy || !line.trim() || p.estimateCredits === null}
        onClick={() => void p.generate(line.trim())}
      >
        {busy ? "Generating…" : clip ? copy.again : copy.cta}
        <AvatarCreditCost credits={p.estimateCredits} />
      </Button>

      {busy && (
        <div className="flex flex-col gap-1.5">
          <Skeleton className="aspect-[9/16] w-40 rounded-lg" />
          <p className="text-xs text-muted-foreground">
            {mode === "native" ? "Usually a minute or two." : "Usually about a minute."} You can leave this step.
          </p>
        </div>
      )}

      {!busy && clip?.url && (
        <div className="flex flex-col gap-1.5">
          <video
            key={clip.url}
            src={clip.url}
            controls
            playsInline
            preload="metadata"
            className="aspect-[9/16] w-40 rounded-lg border bg-muted object-cover"
          />
          <p className="text-xs text-muted-foreground">
            {clip.voiceName ? `${clip.voiceName} · ` : ""}“{clip.line}”
          </p>
          {isVoicePreviewStale(clip, avatar) && (
            <Badge variant="outline" className="self-start">
              Out of date — the voice or the front image changed
            </Badge>
          )}
        </div>
      )}

      {!busy && mode === "native" && <AvatarVoiceSample sample={avatar.voiceSample} />}

      {!busy && failed && (
        <p className="text-xs text-destructive">
          {failed.error ?? "The preview failed."} No credits were charged.
        </p>
      )}
    </div>
  );
}
